<a href="https://colab.research.google.com/github/asefycom/Machine-Learning-Algorithms/blob/main/utility/multiclass_decision_function_sklearn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

این کد مربوط به درس نهم از فصل سوم آموزش رایگان یادگیری ماشین بر اساس کتاب جرون است.
# برای تماشای فیلم این درس به [این فهرست پخش](https://www.youtube.com/playlist?list=PL6h2BSS40Hh_UvcN1c7fII3GkvjsiLCTe) و فیلم شماره ۲۰ مراجعه کنید.

In [5]:
#Example for multiclass svc (ovo under the hood)
import numpy as np
X = np.array([[-10, -10], [-20, -10], [10, 10], [20, 10]])
y = np.array([1, 4, 2, 3])
from sklearn.svm import SVC
clf = SVC(random_state=42)
clf.fit(X, y)
X_new = [[-10,-10]]
print(clf.decision_function(X_new))
print(clf.predict(X_new))
clf.decision_function_shape = "ovo"
print(clf.decision_function(X_new))

[[ 3.2265795   0.80157869 -0.21343185  2.17671805]]
[1]
[[ 0.89829861  0.97562716  0.24852271  0.07732855 -0.6497759  -0.72710445]]


In [7]:
# ‌Desicion function aggregation process (45 scores to 10 scores)
# Run the code below as a script in a python debugger
import numpy as np
n_classes = 4
confidences = [0.89829861, 0.97562716, 0.24852271, 0.07732855, -0.6497759, -0.727010445]
predictions = [1,   1,   1,   2,   4,   4]
sum_of_confidences = np.zeros(n_classes)
#votes = ?

k = 0
# set a breakpoint at the line below
for i in range(n_classes):
    for j in range(i + 1, n_classes):
        sum_of_confidences[i] -= confidences[k]
        sum_of_confidences[j] += confidences[k]
        #votes???
        k += 1

transformed_confidences = sum_of_confidences / (
    3 * (np.abs(sum_of_confidences) + 1)
)
print(transformed_confidences)
#print(votes + transformed_confidences)
"""Since there is a "-=" operator in the for loop,
it seems that the confidences array must be multiplied by -1"""

[-0.2265795   0.19842131  0.2134278  -0.17671113]


'Since there is a "-=" operator in the for loop, \nit seems that the confidences array must be multiplied by -1'